name: pylint-action
on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    name: Executes pylint
    steps:
      - name: pylint-action-checkout
        uses: actions/checkout@v1

      - name: pylint-action-lint
        uses: gabriel-milan/action-pylint@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # GitHub token
          # path: "./*.py" # Glob pattern for files to lint
          fail: true # Fail the action if pylint errors are found
          pr-message: true # Send a PR message if pylint errors are found
